== Top level fields

The top level fields may be present in every record.


=== message





=== @timestamp





=== hostname





=== ipaddr4





=== ipaddr6





=== level





=== pid





=== service





=== tags





=== file





=== offset





=== namespace_name





=== namespace_uuid





=== viaq_msg_id ⚠


WARNING: Private field for use by logging system, may change or dissapear in future releases.

[horizontal]
Data type:: keyword
Description:: A unique ID assigned to each message.  The format is not specified.
It may be a UUID or a Base64 or some other ascii value.
This is currently generated by
https://github.com/uken/fluent-plugin-elasticsearch/tree/v1.13.2#generate-hash-id
and is used as the `_id` of the document in Elasticsearch.
An intended use of this field is that if you use another logging
store or application other than Elasticsearch, but you still need
to correlate data with the data stored in Elasticsearch, this field
will give you the exact document corresponding to the record.

Example value:: 82f13a8e-882a-4344-b103-f0a6f30fd218




=== viaq_index_name ⚠


WARNING: Private field for use by logging system, may change or dissapear in future releases.

[horizontal]
Data type:: keyword
Description:: For Elasticsearch 6.x and later this is a name of a write index alias. The value depends on a log type
of this message. Detailed documentation is found at
https://github.com/openshift/enhancements/blob/master/enhancements/cluster-logging/cluster-logging-es-rollover-data-design.md#data-model

For Elasticsearch 5.x and earlier an index name in which this message will be stored within the Elasticsearch.
The value of this field is generated based on the source of the message. Example of the value
is 'project.my-cool-project-in-lab04.748e92c2-70d7-11e9-b387-000d3af2d83b.2019.05.09'.

Example value:: container.app-write




=== geoip ⚠


WARNING: Private field for use by logging system, may change or dissapear in future releases.

[horizontal]
Data type:: object
Description:: geo-ip of the machine




